################################################################################
# php-fpm image
################################################################################

FROM registry.gitlab.mlogroup.ru:8443/mlgperspective/models

MAINTAINER dtoch.56@gmail.com

################################################################################
# Build instructions
################################################################################

RUN apk add --no-cache $PHPIZE_DEPS \
	&& pecl install xdebug-2.6.0 \
	&& docker-php-ext-enable xdebug
RUN apk del $PHPIZE_DEPS

RUN rm -rf /var/cache/apk/*
