vich_uploader:
    db_driver: orm

    mappings:
        models:
            uri_prefix: '%model_images_web_folder%'
            namer: Model\Naming\PhotoFileNamer
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            upload_destination: '%kernel.project_dir%/public/images/models'
