# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'ru'
    model_images_web_folder: '/images/models'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../modules/App/src/*'
        exclude: '../modules/App/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../modules/App/src/Controller'
        tags: ['controller.service_arguments']

    Model\:
        resource: '../modules/Model/src/*'
        exclude: '../modules/Model/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Model\Controller\:
        resource: '../modules/Model/src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Model\Naming\PhotoFileNamer:
        public: true

    Model\EventListener\CreateNewModelPurchasePriceListener:
        arguments: ['@Model\Calculator\PurchasePriceCalculator']
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Model\EventListener\ModelEventListener:
          arguments: ['%model_images_web_folder%']
          tags:
              - { name: doctrine.event_listener, event: postLoad }